### ISSUE TITLE
Poor performance

### ISSUE THREAD

**Issue by unckleg** [Picsart-AI-Research/LIVE-Layerwise-Image-Vectorization#7]
Hi, @ma-xu @honghuis great work on this one. Thank you and thanks to the other contributors! 

I have a few questions/concerns:

So I just wanted to check what is estimated optimal time in minutes/seconds for getting just the SVG output for this example **on your side ?**: 
```bash 
python main.py --config config/base.yaml --experiment experiment_5x1 --signature smile --target figures/smile.png --log_dir log/
``` 

I'm asking this because when I run the experiment for that specific example I'm getting the results after 20 minutes or much more. 

Also if I run an experiment with for example image down below I wait for hours and don't know where to look to try to optimize the code if possible or if that is expected ? :thinking: : 
![1](https://user-images.githubusercontent.com/10105499/216096995-23da47a4-c558-44ad-a846-78c6ffd8fcf4.png)

**Comment by ma-xu** [comment]
@unckleg Thanks for your interest.
1. First, please check if you are using the GPUs for inference. CPU would run much slower than GPUs. 
2. experiment_5x1 only has 5 paths, and you may need to try more paths for complex images. I can do one for you by the end of this week.

**Comment by unckleg** [comment]
@ma-xu 

Thank you for your reply :) 
I'm going to resize the image and compress it to be much smaller and run experiments again. 

Here are some findings I did while testing both locally and on GCP.

[GCP](https://www.google.com/aclk?sa=l&ai=DChcSEwi-m7Po-vj8AhWiBnsKHd--C_UYABABGgJsZQ&sig=AOD64_0pywlCD6CeclF6EzMyuFfPlqdakQ&q&adurl&ved=2ahUKEwj0pazo-vj8AhWUgSoKHeMsBCsQ0Qx6BAgGEAE):
- 48 vCPU + 340 GB memory  
- 4 [NVIDIA A100](https://www.nvidia.com/en-us/data-center/a100/) 40GB + 4 GPUs
- 10 GB balanced persistent disk (Debian with CUDA 11.0 M100)
```yaml
default:
  use_ycrcb: False
  seginit:
    type: circle
    radius: 5
  save:
    init: false
    image: false
    output: true
    video: false
    loss: false
  trainable: 
    bg: False
    record: True
    stroke: False
  num_iter: 125
experiment_fast:
  path_schedule:
    type: list
    schedule: [50, 50, 50, 50]
```
Running the script there with this config and the configuration above took around 1H and I got this as the output (**Num iter is 125**):
![1](https://svgur.com/i/q11.svg)

Locally on my machine using just RAM and CPU also took around 1H with the same yaml and got almost the same results.

Now I've put **512** for num_iter on GCP and it's still processing outputs for the whole night, yet didn't complete and this is last  result (Note that it's running for 10h now and this is last output :hammer:)
![1](https://svgur.com/i/q0g.svg)


I'm just curious how much time It took on your side to get this SVG output from your examples:
![demo2](https://user-images.githubusercontent.com/10105499/216554852-47793c7c-eed4-4b85-91d2-6f0260f0bef4.jpg)

Thanks a lot!
